In [1]:
import pandas as pd
import numpy as np

In [72]:
df1 = pd.read_excel('./data/감성대화말뭉치AI데이터_평가용Wave_대본1만문장.xlsx', engine='openpyxl')

In [73]:
df2 = pd.read_csv('./data/감정분류점수1.csv', encoding='cp949')

In [74]:
df1.head()

,연령,성별,상황키워드,감정_대분류,감정_소분류,사람문장1,기계문장1,사람문장2,기계문장2,사람문장3,기계문장3
0,청소년,남성,학업 및 진로,기쁨,감사하는,오늘 반장 선거에서 내가 반장이 됐어! 친구들이 날 믿어줘서 너무 고맙다.,오늘 바라던 반장이 되셨군요. 정말 기쁘시겠어요.,친구들에게 어떻게 보답하면 좋을지 고민이야.,고마움을 표현하고 싶으시군요. 어떻게 보답하면 좋을까요?,친구 한 명씩 찾아가서 고맙다고 말하고 바라는 점을 물어보면 좋을 것 같아.,친구들이 좋아하고 훌륭한 반장이 되셨으면 좋겠네요.
1,청소년,남성,학업 및 진로,기쁨,감사하는,오늘 시험에 친구가 알려준 문제가 나왔어. 결과가 좋아서 기쁘다.,오늘 시험을 잘 보셔서 기쁘시군요. 친구에겐 뭐라고 고마움을 표시할 건가요?,말로 하기 쑥스러운데.,쑥스럽다면 어떻게 표현하는 게 좋을까요?,같이 떡볶이 먹고 피시방 가자고 해야겠어.,친구와 즐거운 시간 되길 바라요.
2,청소년,남성,학업 및 진로,기쁨,감사하는,오늘 대학 합격 통지를 받았어. 엄마가 너무 기뻐하는데 나는 눈물이 났어.,오늘 대학 합격 소식을 듣게 되어 정말 기쁘시겠어요.,사실 이렇게 대학에 들어갈 수 있게 된 것도 엄마 덕분이야. 나 때문에 고생 많이 ...,어머니께 감사함을 느끼시는군요. 어떻게 하면 어머니께 감사한 마음을 전달할 수 있을까요?,오늘은 내가 설거지랑 청소를 해야겠어. 사랑한다는 말도.,깨끗한 집을 보고 어머니께서 기뻐하시면 좋겠어요.
3,청소년,남성,학업 및 진로,기쁨,감사하는,오늘 졸업식인데 선생님께서 아프셔서 오지 못하셨어. 그동안 감사하다는 말도 못했는데.,졸업식에 선생님을 못 뵈어 아쉬웠겠어요.,그동안 말썽도 많이 피웠는데 한 번도 크게 화내신 적이 없었어. 졸업식에서야 선생님...,감사함을 표현하지 못해 아쉬운 마음이시군요. 어떻게 감사한 마음을 전달할 수 있을까요?,너무 감사했다고 지금 문자라도 보내야겠어.,선생님께서 문자를 받으시고 기뻐하시면 좋겠어요.
4,청소년,남성,학업 및 진로,기쁨,감사하는,나 올림피아드에서 금상 받았어! 그동안 고생이 헛되지 않아서 너무 기뻐.,그동안 고생했는데 금상 수상까지 하셔서 정말 기쁘시겠어요.,근데 친구들이 없었다면 못 했을 거야. 대회장에서 처음부터 끝까지 응원해 줘서 너무...,친구들 덕분에 큰 힘을 받으셨군요. 친구들에게는 어떻게 고마움을 표현하실 건가요?,내일 저녁에 빕스에서 저녁을 살 거야.,친구들과 즐거운 저녁식사가 되었으면 좋겠어요.

In [75]:
df3=df1.replace({'감정_소분류':'혼란스러운(당황한)'},{'감정_소분류':'혼란스러운'})

In [6]:
df3.head()

,연령,성별,상황키워드,감정_대분류,감정_소분류,사람문장1,기계문장1,사람문장2,기계문장2,사람문장3,기계문장3
0,청소년,남성,학업 및 진로,기쁨,감사하는,오늘 반장 선거에서 내가 반장이 됐어! 친구들이 날 믿어줘서 너무 고맙다.,오늘 바라던 반장이 되셨군요. 정말 기쁘시겠어요.,친구들에게 어떻게 보답하면 좋을지 고민이야.,고마움을 표현하고 싶으시군요. 어떻게 보답하면 좋을까요?,친구 한 명씩 찾아가서 고맙다고 말하고 바라는 점을 물어보면 좋을 것 같아.,친구들이 좋아하고 훌륭한 반장이 되셨으면 좋겠네요.
1,청소년,남성,학업 및 진로,기쁨,감사하는,오늘 시험에 친구가 알려준 문제가 나왔어. 결과가 좋아서 기쁘다.,오늘 시험을 잘 보셔서 기쁘시군요. 친구에겐 뭐라고 고마움을 표시할 건가요?,말로 하기 쑥스러운데.,쑥스럽다면 어떻게 표현하는 게 좋을까요?,같이 떡볶이 먹고 피시방 가자고 해야겠어.,친구와 즐거운 시간 되길 바라요.
2,청소년,남성,학업 및 진로,기쁨,감사하는,오늘 대학 합격 통지를 받았어. 엄마가 너무 기뻐하는데 나는 눈물이 났어.,오늘 대학 합격 소식을 듣게 되어 정말 기쁘시겠어요.,사실 이렇게 대학에 들어갈 수 있게 된 것도 엄마 덕분이야. 나 때문에 고생 많이 ...,어머니께 감사함을 느끼시는군요. 어떻게 하면 어머니께 감사한 마음을 전달할 수 있을까요?,오늘은 내가 설거지랑 청소를 해야겠어. 사랑한다는 말도.,깨끗한 집을 보고 어머니께서 기뻐하시면 좋겠어요.
3,청소년,남성,학업 및 진로,기쁨,감사하는,오늘 졸업식인데 선생님께서 아프셔서 오지 못하셨어. 그동안 감사하다는 말도 못했는데.,졸업식에 선생님을 못 뵈어 아쉬웠겠어요.,그동안 말썽도 많이 피웠는데 한 번도 크게 화내신 적이 없었어. 졸업식에서야 선생님...,감사함을 표현하지 못해 아쉬운 마음이시군요. 어떻게 감사한 마음을 전달할 수 있을까요?,너무 감사했다고 지금 문자라도 보내야겠어.,선생님께서 문자를 받으시고 기뻐하시면 좋겠어요.
4,청소년,남성,학업 및 진로,기쁨,감사하는,나 올림피아드에서 금상 받았어! 그동안 고생이 헛되지 않아서 너무 기뻐.,그동안 고생했는데 금상 수상까지 하셔서 정말 기쁘시겠어요.,근데 친구들이 없었다면 못 했을 거야. 대회장에서 처음부터 끝까지 응원해 줘서 너무...,친구들 덕분에 큰 힘을 받으셨군요. 친구들에게는 어떻게 고마움을 표현하실 건가요?,내일 저녁에 빕스에서 저녁을 살 거야.,친구들과 즐거운 저녁식사가 되었으면 좋겠어요.

In [76]:
df4=df3.replace({'감정_소분류':'고립된(당황한)'},{'감정_소분류':'고립된'})

In [77]:
df5=df4.replace({'감정_소분류':'구역질나는'},{'감정_소분류':'구역질 나는'})

In [78]:
df6=df5.replace({'감정_소분류':'가난한, 불우한'},{'감정_소분류':'불우한'})

In [79]:
df7=df6.replace({'감정_소분류':'스트레스받는'},{'감정_소분류':'스트레스 받는'})

In [80]:
df8=df7.replace({'감정_소분류':'충격받은'},{'감정_소분류':'충격 받은'})

In [81]:
df8.head()

,연령,성별,상황키워드,감정_대분류,감정_소분류,사람문장1,기계문장1,사람문장2,기계문장2,사람문장3,기계문장3
0,청소년,남성,학업 및 진로,기쁨,감사하는,오늘 반장 선거에서 내가 반장이 됐어! 친구들이 날 믿어줘서 너무 고맙다.,오늘 바라던 반장이 되셨군요. 정말 기쁘시겠어요.,친구들에게 어떻게 보답하면 좋을지 고민이야.,고마움을 표현하고 싶으시군요. 어떻게 보답하면 좋을까요?,친구 한 명씩 찾아가서 고맙다고 말하고 바라는 점을 물어보면 좋을 것 같아.,친구들이 좋아하고 훌륭한 반장이 되셨으면 좋겠네요.
1,청소년,남성,학업 및 진로,기쁨,감사하는,오늘 시험에 친구가 알려준 문제가 나왔어. 결과가 좋아서 기쁘다.,오늘 시험을 잘 보셔서 기쁘시군요. 친구에겐 뭐라고 고마움을 표시할 건가요?,말로 하기 쑥스러운데.,쑥스럽다면 어떻게 표현하는 게 좋을까요?,같이 떡볶이 먹고 피시방 가자고 해야겠어.,친구와 즐거운 시간 되길 바라요.
2,청소년,남성,학업 및 진로,기쁨,감사하는,오늘 대학 합격 통지를 받았어. 엄마가 너무 기뻐하는데 나는 눈물이 났어.,오늘 대학 합격 소식을 듣게 되어 정말 기쁘시겠어요.,사실 이렇게 대학에 들어갈 수 있게 된 것도 엄마 덕분이야. 나 때문에 고생 많이 ...,어머니께 감사함을 느끼시는군요. 어떻게 하면 어머니께 감사한 마음을 전달할 수 있을까요?,오늘은 내가 설거지랑 청소를 해야겠어. 사랑한다는 말도.,깨끗한 집을 보고 어머니께서 기뻐하시면 좋겠어요.
3,청소년,남성,학업 및 진로,기쁨,감사하는,오늘 졸업식인데 선생님께서 아프셔서 오지 못하셨어. 그동안 감사하다는 말도 못했는데.,졸업식에 선생님을 못 뵈어 아쉬웠겠어요.,그동안 말썽도 많이 피웠는데 한 번도 크게 화내신 적이 없었어. 졸업식에서야 선생님...,감사함을 표현하지 못해 아쉬운 마음이시군요. 어떻게 감사한 마음을 전달할 수 있을까요?,너무 감사했다고 지금 문자라도 보내야겠어.,선생님께서 문자를 받으시고 기뻐하시면 좋겠어요.
4,청소년,남성,학업 및 진로,기쁨,감사하는,나 올림피아드에서 금상 받았어! 그동안 고생이 헛되지 않아서 너무 기뻐.,그동안 고생했는데 금상 수상까지 하셔서 정말 기쁘시겠어요.,근데 친구들이 없었다면 못 했을 거야. 대회장에서 처음부터 끝까지 응원해 줘서 너무...,친구들 덕분에 큰 힘을 받으셨군요. 친구들에게는 어떻게 고마움을 표현하실 건가요?,내일 저녁에 빕스에서 저녁을 살 거야.,친구들과 즐거운 저녁식사가 되었으면 좋겠어요.

In [82]:
df2.head()

,Unnamed: 0,category,anger,Anticipation,Joy,Trust,Fear,Surprise,Sadness,Disgust
0,1,"가난한, 불우한",16.666667,0.0,0.0,0.0,30.0,17.5,57.5,25.0
1,2,감사하는,0.000000,2.5,57.5,85.0,0.0,22.5,0.0,0.0
2,3,걱정스러운,7.500000,45.0,0.0,0.0,62.5,15.0,25.0,12.5
3,4,고립된,7.500000,12.5,0.0,0.0,55.0,17.5,15.0,12.5
4,5,괴로워하는,20.000000,0.0,0.0,0.0,42.5,17.5,70.0,35.0

In [106]:
df2=df2.replace({'category':'가난한, 불우한'},{'category':'불우한'})

In [107]:
df2.head()

,Unnamed: 0,category,anger,Anticipation,Joy,Trust,Fear,Surprise,Sadness,Disgust
0,1,불우한,16.666667,0.0,0.0,0.0,30.0,17.5,57.5,25.0
1,2,감사하는,0.000000,2.5,57.5,85.0,0.0,22.5,0.0,0.0
2,3,걱정스러운,7.500000,45.0,0.0,0.0,62.5,15.0,25.0,12.5
3,4,고립된,7.500000,12.5,0.0,0.0,55.0,17.5,15.0,12.5
4,5,괴로워하는,20.000000,0.0,0.0,0.0,42.5,17.5,70.0,35.0

In [108]:
# 데이터 일부분만 사용
data1 = df8[['감정_소분류','사람문장1','사람문장2','사람문장3']]

In [109]:
data1.rename(columns={'감정_소분류':'category'}, inplace=True)

C:\Anaconda3\lib\site-packages\pandas\core\frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [110]:
data2 = df2[['category','anger','Anticipation','Joy','Trust','Fear','Surprise','Sadness','Disgust']]

In [111]:
data1.head()

,category,사람문장1,사람문장2,사람문장3
0,감사하는,오늘 반장 선거에서 내가 반장이 됐어! 친구들이 날 믿어줘서 너무 고맙다.,친구들에게 어떻게 보답하면 좋을지 고민이야.,친구 한 명씩 찾아가서 고맙다고 말하고 바라는 점을 물어보면 좋을 것 같아.
1,감사하는,오늘 시험에 친구가 알려준 문제가 나왔어. 결과가 좋아서 기쁘다.,말로 하기 쑥스러운데.,같이 떡볶이 먹고 피시방 가자고 해야겠어.
2,감사하는,오늘 대학 합격 통지를 받았어. 엄마가 너무 기뻐하는데 나는 눈물이 났어.,사실 이렇게 대학에 들어갈 수 있게 된 것도 엄마 덕분이야. 나 때문에 고생 많이 ...,오늘은 내가 설거지랑 청소를 해야겠어. 사랑한다는 말도.
3,감사하는,오늘 졸업식인데 선생님께서 아프셔서 오지 못하셨어. 그동안 감사하다는 말도 못했는데.,그동안 말썽도 많이 피웠는데 한 번도 크게 화내신 적이 없었어. 졸업식에서야 선생님...,너무 감사했다고 지금 문자라도 보내야겠어.
4,감사하는,나 올림피아드에서 금상 받았어! 그동안 고생이 헛되지 않아서 너무 기뻐.,근데 친구들이 없었다면 못 했을 거야. 대회장에서 처음부터 끝까지 응원해 줘서 너무...,내일 저녁에 빕스에서 저녁을 살 거야.

In [112]:
data1.tail()

,category,사람문장1,사람문장2,사람문장3
9995,환멸을 느끼는,소득이 너무 적어서 제대로 된 노후 대책을 할 수가 없어 힘들어.,백세시대라 노후를 잘 대비해야 하는데 걱정이 이만저만이 아니야.,불필요한 소비를 좀 더 줄이고 술 담배도 줄여서 최대한 아끼며 생활을 해야겠어.
9996,충격 받은,요즘 두통이 잦았는데 결국 이런 일이 생겼네. 난 건강한 줄 알았는데 충격받았어.,두통 때문에 병원에 갔는데 뇌척수막염 치료 시기를 놓쳤대. 눈앞이 캄캄해.,슬프지만 받아들이고 아내한테 이야기해야겠지.
9997,걱정스러운,친구가 돈이 행복의 전부가 아니라고 하더니 노후 준비를 전혀 안 한 거야. 어휴 정...,여태 노후 준비를 하나도 안 해놓다니 어쩌려고 그러는지 모르겠어.,친구에게 돈이 중요하다고 다시 한번 충고해줘야 할 것 같아.
9998,두려운,아들이 갑자기 찾아왔는데 손자가 희귀병이래. 너무 두려워.,아직 치료법도 없대. 아직 어린데 입원해 있을 생각을 하니 눈물이 나.,손자 입원하면 자주 찾아가고 간호해야지.
9999,남의 시선을 의식하는,친구들에게는 자식이 선물해 줬다고 했지만 사실은 다 내가 구입한 거야.,자식들에게 좋은 대접을 받는다고 말하고 싶어서 거짓말을 했던 것 같아.,일단은 가까운 친구들에게라도 솔직하게 털어놓도록 노력해 봐야겠어.

In [113]:
data2.head()

,category,anger,Anticipation,Joy,Trust,Fear,Surprise,Sadness,Disgust
0,불우한,16.666667,0.0,0.0,0.0,30.0,17.5,57.5,25.0
1,감사하는,0.000000,2.5,57.5,85.0,0.0,22.5,0.0,0.0
2,걱정스러운,7.500000,45.0,0.0,0.0,62.5,15.0,25.0,12.5
3,고립된,7.500000,12.5,0.0,0.0,55.0,17.5,15.0,12.5
4,괴로워하는,20.000000,0.0,0.0,0.0,42.5,17.5,70.0,35.0

In [114]:
data3 = data1[['category','사람문장1']]

In [115]:
data4 = data1[['category','사람문장2']]

In [116]:
data5 = data1[['category','사람문장3']]

In [117]:
data3.rename(columns={'사람문장1':'text'}, inplace=True)

C:\Anaconda3\lib\site-packages\pandas\core\frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [118]:
data4.rename(columns={'사람문장2':'text'}, inplace=True)

In [119]:
data5.rename(columns={'사람문장3':'text'}, inplace=True)

In [120]:
data3.head()

  category                                             text
0     감사하는        오늘 반장 선거에서 내가 반장이 됐어! 친구들이 날 믿어줘서 너무 고맙다.
1     감사하는             오늘 시험에 친구가 알려준 문제가 나왔어. 결과가 좋아서 기쁘다.
2     감사하는        오늘 대학 합격 통지를 받았어. 엄마가 너무 기뻐하는데 나는 눈물이 났어.
3     감사하는  오늘 졸업식인데 선생님께서 아프셔서 오지 못하셨어. 그동안 감사하다는 말도 못했는데.
4     감사하는         나 올림피아드에서 금상 받았어! 그동안 고생이 헛되지 않아서 너무 기뻐.

In [121]:
data4.head()

  category                                               text
0     감사하는                           친구들에게 어떻게 보답하면 좋을지 고민이야.
1     감사하는                                       말로 하기 쑥스러운데.
2     감사하는  사실 이렇게 대학에 들어갈 수 있게 된 것도 엄마 덕분이야. 나 때문에 고생 많이 ...
3     감사하는  그동안 말썽도 많이 피웠는데 한 번도 크게 화내신 적이 없었어. 졸업식에서야 선생님...
4     감사하는  근데 친구들이 없었다면 못 했을 거야. 대회장에서 처음부터 끝까지 응원해 줘서 너무...

In [122]:
data5.tail()

         category                                          text
9995      환멸을 느끼는  불필요한 소비를 좀 더 줄이고 술 담배도 줄여서 최대한 아끼며 생활을 해야겠어.
9996        충격 받은                      슬프지만 받아들이고 아내한테 이야기해야겠지.
9997        걱정스러운             친구에게 돈이 중요하다고 다시 한번 충고해줘야 할 것 같아.
9998          두려운                        손자 입원하면 자주 찾아가고 간호해야지.
9999  남의 시선을 의식하는          일단은 가까운 친구들에게라도 솔직하게 털어놓도록 노력해 봐야겠어.

In [123]:
result1=pd.merge(data2, data3, on='category', how='left')

In [124]:
result1.head()

,category,anger,Anticipation,Joy,Trust,Fear,Surprise,Sadness,Disgust,text
0,불우한,16.666667,0.0,0.0,0.0,30.0,17.5,57.5,25.0,우리 집이 잘 못산다는 것을 친구들이 알게 되었을 때 정말 억장이 무너지는 것 같았어.
1,불우한,16.666667,0.0,0.0,0.0,30.0,17.5,57.5,25.0,학급비를 내지 못하고 있을 때 친구들에게 따돌림을 당할까봐 심장이 조마조마 했어.
2,불우한,16.666667,0.0,0.0,0.0,30.0,17.5,57.5,25.0,부모님의 지갑을 보고 나니 체험학습 비 달라는 말을 못하겠어.
3,불우한,16.666667,0.0,0.0,0.0,30.0,17.5,57.5,25.0,우리 집이 불우한 것이 친구들 사이에선 놀림거리로 여겨지고 있어.
4,불우한,16.666667,0.0,0.0,0.0,30.0,17.5,57.5,25.0,내가 돈이 없는 것으로 인해 따돌림 당한다는 사실을 부모님이 알아버리셨어

In [125]:
result2=pd.merge(data2, data4, on='category', how='left')

In [126]:
result3=pd.merge(data2, data5, on='category', how='left')

In [127]:
result2.head()

,category,anger,Anticipation,Joy,Trust,Fear,Surprise,Sadness,Disgust,text
0,불우한,16.666667,0.0,0.0,0.0,30.0,17.5,57.5,25.0,창피해서 친구들과 마주하고 싶지 않아. 날 보고 수군거릴 것만 같아.
1,불우한,16.666667,0.0,0.0,0.0,30.0,17.5,57.5,25.0,돈이 없어서 학급비를 못 낸다는 게 너무 비참해.
2,불우한,16.666667,0.0,0.0,0.0,30.0,17.5,57.5,25.0,집안 사정이 좋지 않아서 체험학습비가 필요하다고 말씀드려야 하는데 입이 떨어지질 않더라.
3,불우한,16.666667,0.0,0.0,0.0,30.0,17.5,57.5,25.0,너무 속상해서 친구들을 안보고 살고 싶어.
4,불우한,16.666667,0.0,0.0,0.0,30.0,17.5,57.5,25.0,많이 속상해 하시고 나한테 미안해서 어쩔 줄 모르셔.

In [128]:
result3.tail()

,category,anger,Anticipation,Joy,Trust,Fear,Surprise,Sadness,Disgust,text
9995,희생된,12.5,0.0,0.0,0.0,40.0,22.5,82.5,25.0,딸과 전화통화를 해야겠어.
9996,희생된,12.5,0.0,0.0,0.0,40.0,22.5,82.5,25.0,가족들에게 솔직하게 말해 봐야겠어.
9997,희생된,12.5,0.0,0.0,0.0,40.0,22.5,82.5,25.0,남편에게 솔직하게 말해 봐야겠어.
9998,희생된,12.5,0.0,0.0,0.0,40.0,22.5,82.5,25.0,나보다 더 아픈 남편도 있는데 내가 그러면 안 된다고 스스로 다독이면 괜찮을 거야.
9999,희생된,12.5,0.0,0.0,0.0,40.0,22.5,82.5,25.0,딸에게 사랑한다고 말할 거야. 같이 외출도 해서 기분 전환을 하고 싶어.

In [129]:
result=pd.concat([result1, result2,result3], axis = 0)

In [130]:
result.head()

,category,anger,Anticipation,Joy,Trust,Fear,Surprise,Sadness,Disgust,text
0,불우한,16.666667,0.0,0.0,0.0,30.0,17.5,57.5,25.0,우리 집이 잘 못산다는 것을 친구들이 알게 되었을 때 정말 억장이 무너지는 것 같았어.
1,불우한,16.666667,0.0,0.0,0.0,30.0,17.5,57.5,25.0,학급비를 내지 못하고 있을 때 친구들에게 따돌림을 당할까봐 심장이 조마조마 했어.
2,불우한,16.666667,0.0,0.0,0.0,30.0,17.5,57.5,25.0,부모님의 지갑을 보고 나니 체험학습 비 달라는 말을 못하겠어.
3,불우한,16.666667,0.0,0.0,0.0,30.0,17.5,57.5,25.0,우리 집이 불우한 것이 친구들 사이에선 놀림거리로 여겨지고 있어.
4,불우한,16.666667,0.0,0.0,0.0,30.0,17.5,57.5,25.0,내가 돈이 없는 것으로 인해 따돌림 당한다는 사실을 부모님이 알아버리셨어

In [131]:
result.tail()

,category,anger,Anticipation,Joy,Trust,Fear,Surprise,Sadness,Disgust,text
9995,희생된,12.5,0.0,0.0,0.0,40.0,22.5,82.5,25.0,딸과 전화통화를 해야겠어.
9996,희생된,12.5,0.0,0.0,0.0,40.0,22.5,82.5,25.0,가족들에게 솔직하게 말해 봐야겠어.
9997,희생된,12.5,0.0,0.0,0.0,40.0,22.5,82.5,25.0,남편에게 솔직하게 말해 봐야겠어.
9998,희생된,12.5,0.0,0.0,0.0,40.0,22.5,82.5,25.0,나보다 더 아픈 남편도 있는데 내가 그러면 안 된다고 스스로 다독이면 괜찮을 거야.
9999,희생된,12.5,0.0,0.0,0.0,40.0,22.5,82.5,25.0,딸에게 사랑한다고 말할 거야. 같이 외출도 해서 기분 전환을 하고 싶어.

In [132]:
result_r = result[['category','text','anger','Anticipation','Joy','Trust','Fear','Surprise','Sadness','Disgust']]

In [133]:
result_r.head()

,category,text,anger,Anticipation,Joy,Trust,Fear,Surprise,Sadness,Disgust
0,불우한,우리 집이 잘 못산다는 것을 친구들이 알게 되었을 때 정말 억장이 무너지는 것 같았어.,16.666667,0.0,0.0,0.0,30.0,17.5,57.5,25.0
1,불우한,학급비를 내지 못하고 있을 때 친구들에게 따돌림을 당할까봐 심장이 조마조마 했어.,16.666667,0.0,0.0,0.0,30.0,17.5,57.5,25.0
2,불우한,부모님의 지갑을 보고 나니 체험학습 비 달라는 말을 못하겠어.,16.666667,0.0,0.0,0.0,30.0,17.5,57.5,25.0
3,불우한,우리 집이 불우한 것이 친구들 사이에선 놀림거리로 여겨지고 있어.,16.666667,0.0,0.0,0.0,30.0,17.5,57.5,25.0
4,불우한,내가 돈이 없는 것으로 인해 따돌림 당한다는 사실을 부모님이 알아버리셨어,16.666667,0.0,0.0,0.0,30.0,17.5,57.5,25.0

In [134]:
result_r.tail()

,category,text,anger,Anticipation,Joy,Trust,Fear,Surprise,Sadness,Disgust
9995,희생된,딸과 전화통화를 해야겠어.,12.5,0.0,0.0,0.0,40.0,22.5,82.5,25.0
9996,희생된,가족들에게 솔직하게 말해 봐야겠어.,12.5,0.0,0.0,0.0,40.0,22.5,82.5,25.0
9997,희생된,남편에게 솔직하게 말해 봐야겠어.,12.5,0.0,0.0,0.0,40.0,22.5,82.5,25.0
9998,희생된,나보다 더 아픈 남편도 있는데 내가 그러면 안 된다고 스스로 다독이면 괜찮을 거야.,12.5,0.0,0.0,0.0,40.0,22.5,82.5,25.0
9999,희생된,딸에게 사랑한다고 말할 거야. 같이 외출도 해서 기분 전환을 하고 싶어.,12.5,0.0,0.0,0.0,40.0,22.5,82.5,25.0

In [135]:
print(result_r)

     category                                              text      anger  \
0         불우한  우리 집이 잘 못산다는 것을 친구들이 알게 되었을 때 정말 억장이 무너지는 것 같았어.  16.666667
1         불우한     학급비를 내지 못하고 있을 때 친구들에게 따돌림을 당할까봐 심장이 조마조마 했어.  16.666667
2         불우한                부모님의 지갑을 보고 나니 체험학습 비 달라는 말을 못하겠어.  16.666667
3         불우한              우리 집이 불우한 것이 친구들 사이에선 놀림거리로 여겨지고 있어.  16.666667
4         불우한          내가 돈이 없는 것으로 인해 따돌림 당한다는 사실을 부모님이 알아버리셨어  16.666667
...       ...                                               ...        ...
9995      희생된                                    딸과 전화통화를 해야겠어.  12.500000
9996      희생된                               가족들에게 솔직하게 말해 봐야겠어.  12.500000
9997      희생된                                남편에게 솔직하게 말해 봐야겠어.  12.500000
9998      희생된    나보다 더 아픈 남편도 있는데 내가 그러면 안 된다고 스스로 다독이면 괜찮을 거야.  12.500000
9999      희생된          딸에게 사랑한다고 말할 거야. 같이 외출도 해서 기분 전환을 하고 싶어.  12.500000

      Anticipation  Joy  Trust  Fear  Surprise  Sadness  Disgust
0              0.0  0.0    0.0  30.0      17.5     57.5     25.0
1              0.0  0.0    0.0  30.0      17.5     57.5     25.0
2              0.0  0.0    0.0  30.0      17.5     57.5     25.0
3              0.0  0.0    0.0  30.0      17.5     57.5     25.0
4              0.0  0.0    0.0  30.0      17.5     57.5     25.0
...            ...  ...    ...   ...       ...      ...      ...
9995           0.0  0.0    0.0  40.0      22.5     82.5     25.0
9996           0.0  0.0    0.0  40.0      22.5     82.5     25.0
9997           0.0  0.0    0.0  40.0      22.5     82.5     25.0
9998           0.0  0.0    0.0  40.0      22.5     82.5     25.0
9999           0.0  0.0    0.0  40.0      22.5     82.5     25.0

[30000 rows x 10 columns]

In [142]:
result_r.to_excel('./감성대화말뭉치_원천데이터_전처리.xlsx')

In [141]:
result_r.to_csv('./감성대화말뭉치_원천데이터_전처리.csv',encoding='utf-8-sig')